name: "Backend CI"

on:
  push:
    branches: [ "master" ]
    paths:
      - .github/workflows/backend-ci.yml
      - backend/**
  pull_request:
    branches: [ "master" ]
    paths:
      - .github/workflows/backend-ci.yml
      - backend/**

defaults:
  run:
    working-directory: 'backend'


jobs:
  build-app:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'
    - name: Install dependencies
      run: npm ci
    - name: Test app
      run: npm run test
      env:
        DATABASE_HOST: localhost
        DATABASE_PORT: 5555
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        SESSION_SECRET: "testSecret"

