name: "Frontend CI"

on:
  push:
    branches: [ "master" ]
    paths:
      - .github/workflows/backend-ci.yml
      - frontend/**
  pull_request:
    branches: [ "master" ]
    paths:
      - .github/workflows/backend-ci.yml
      - fronend/**

defaults:
  run:
    working-directory: 'frontend'

jobs:
  build-app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    - name: Install dependencies
      run: npm ci
    - name: Test app
      run: npm run test

